#!/bin/env python3

import argparse
import re
import os
import logging

import matplotlib.colors
import matplotlib.patches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import ndimage
import readmet

import meteolib

try:
    from . import _dispersion
except ImportError:
    import _dispersion

try:
    from ._version import __version__
except ImportError:
    from _version import __version__

logging.basicConfig()
logger = logging.getLogger()
logging.getLogger('matplotlib.font_manager').setLevel(logging.ERROR)
logging.getLogger('readmet.dmna').setLevel(logging.ERROR)

# -------------------------------------------------------------------------

N_CLASS = 6
N_EGDE_NODES = 3
MIN_FF = 0.5
MIN_XY = 400 * 400
DEFAULT_COLORMAP = "YlOrRd"

# -------------------------------------------------------------------------


def cli():
    # defaults
    default = {
        'path': '.',
        'fewcols': True,
        'display': "contour",
    }
    parser = argparse.ArgumentParser(
        description='find substitute anemometer position ' +
                    'according to VDI 3783 Part 16 ' +
                    'from a wind library generated by austal')
    parser.add_argument('-d', '--display',
                        default='contour',
                        choices=['contour', 'grid'],
                        help='choose kind of display. ' +
                             '`contour` produces filled contours, ' +
                             '`grid` produces coloured grid cells. ' +
                             'Defaults to `contour`')
    parser.add_argument('-c', '--colormap',
                        default=DEFAULT_COLORMAP,
                        help='name of colormap to use. Defaults to "%s"' %
                             DEFAULT_COLORMAP)
    parser.add_argument('-l', '--low-colors',
                        dest='fewcols',
                        action='store_true',
                        help='use only few discrete colors ' +
                             'for better print results')
    parser.add_argument('-p', '--plot',
                        metavar="PLOTFILE",
                        nargs='?',
                        const='__default__',
                        help='save plot to a file. If given without ' +
                             '`PLOT`, the plot will be shown instead ' +
                             'of saving it to a file'
                        )
    parser.add_argument('-r', '--recreate',
                        action='store_true',
                        default=False,
                        help='recreate (overwrite) plotfile if it exists.')
    verb = parser.add_mutually_exclusive_group()
    verb.add_argument('--debug', dest='verb', action='store_const',
                      const=logging.DEBUG, help='show informative output')
    verb.add_argument('-v', '--verbose', dest='verb', action='store_const',
                      const=logging.INFO, help='show detailed output')
    parser.add_argument('path', metavar='PATH', nargs='?',
                        help='directory where "zeitreihe.dmna" is stored '
                             '[%s]' % default['path'],
                        default=default['path'])
    args = parser.parse_args()
    #
    # logging level
    #
    if args.verb is not None:
        logger.setLevel(args.verb)
    else:
        logger.setLevel(logging.WARNING)
    logger.info(os.path.basename(__file__) + ' version: ' + __version__)

    return vars(args)

def wind_library(path):
    # find directory that contains wind library
    if os.path.basename(path) == "lib":
        # path ist the lib-dir:
        libpath = path
    elif os.path.isdir(os.path.join(path, 'lib')):
        # lib-dir is in path:
        libpath = os.path.join(path, 'lib')
    else:
        logger.info('Warning: directory is NOT named lib')
        libpath = path
    logger.info('reading from directory: %s' % libpath)
    return libpath

def analyze_name(name):
    # grid index
    try:
        grid=int(name[6])
    except (ValueError, IndexError):
        raise ValueError("invalid filename (grid index): %s" % name)
    # wind direction
    try:
        adir = name[3:5]
        if adir == "sn":
            wdir = 18
        elif adir == "we":
            wdir = 27
        else:
            wdir = int(adir)
    except (ValueError, IndexError):
        raise ValueError("invalid filename (wind direction): %s" % name)
    # stability class
    try:
        ak = int(name[1:2])
    except (ValueError, IndexError):
        raise ValueError("invalid filename (stability class): %s" % name)
    return grid, wdir, ak

def wind_files(path):
    # find wind library files
    wn = re.compile("w[0-9asnwe]{7}\.dmna")
    f_name = [x for x in os.listdir(path) if wn.match(x)]
    logger.debug('filenames: %s' % str(f_name))
    f_grid = []
    f_wdir = []
    f_stab = []
    for f in f_name:
        grid, wdir, ak = analyze_name(f)
        f_grid.append(grid)
        f_wdir.append(wdir)
        f_stab.append(ak)
    logger.debug('stabilty classes: %s' % str(f_stab))
    logger.debug('wind directions: %s' % str(f_wdir))
    logger.debug('grid indexes: %s' % str(f_grid))
    return f_name, f_stab, f_wdir, f_grid


def read_wind(file_info, path='.', grid=0):
    f_name, f_stab, f_wdir, f_grid = file_info
    if grid not in f_grid:
        raise ValueError('grid %i not available in data')
    ndir = len(set(f_wdir))
    dirs = sorted(list(set(f_wdir)))
    nstab = len(set(f_stab))
    stabs = sorted(list(set(f_stab)))

    axes = readmet.dmna.DataFile(os.path.join(path, f_name[0])).axes()
    nx = len(axes['x'])
    ny = len(axes['y'])
    nz = len(axes['z'])

    u_grid = np.full((nx, ny, nz, nstab, ndir), np.nan)
    v_grid = np.full((nx, ny, nz, nstab, ndir), np.nan)

    for i in range(len(f_name)):
        igrd, wdir, stab = analyze_name(f_name[i])
        if grid == igrd:
            filename = os.path.join(path, f_name[i])
            logger.debug('loading file: %s' % filename)
            dmna = readmet.dmna.DataFile(filename)
            istab = stabs.index(stab)
            idir = dirs.index(wdir)
            u_grid[:,:,:,istab,idir] = dmna.data['Vx']
            v_grid[:,:,:,istab,idir] = dmna.data['Vy']

    return u_grid, v_grid, axes

def same_sense_rotation(val, ref):
    """
    return true if directions (in degrees) in
    val and ref both rotate in the same direction

    :param val: (array of float) tested wind directions
    :param ref: (array of float) reference wind directions
    :returns bool: Sense ist the same
    """
    val_diff = np.sign(np.diff(val % 360.))
    ref_diff = np.sign(np.diff(ref % 360.))
    if all(ref_diff >= 0):
        sense = +1
    elif all(ref_diff <= 0):
        sense = -1
    else:
        #logger.warning("wind reference not sorted: %s" % str(ref))
        sense = 0
    if all(val_diff >= 0) and sense > 0:
        res = True
    elif all(val_diff <= 0) and sense < 0:
        res = True
    else:
        res = False
    return res


def calc_quality_measure(u_grid, v_grid, u_ref, v_ref):
    """
    :param u_grid: np.array of wind field eastward components
    :param v_grid: np.array of wind field northward components
    :param u_ref: np.array of reference wind eastward component
    :param v_ref: np.array of reference wind northward component

    shape of wind fields: (nx, ny, nz, nstab, ndir)
    shape of reference wind profiles: (nz, nstab, ndir)
    levels of wind fields must match heights of the reference wind profiles
    """
    #
    # check if wind grid sizes do match:
    if not (np.shape(u_grid) == np.shape(v_grid)):
        raise ValueError('wind grid shapes do not match')
    nx, ny, nz, nstab, ndir = np.shape(u_grid)
    # check if reference wind grid sizes do match:
    if not (np.shape(u_ref) == np.shape(v_ref)):
        raise ValueError('wind grid shapes do not match')
    if not (nz, nstab, ndir) == np.shape(u_ref):
        raise ValueError('wind grid shape does not match wind grid shape')

    # create result
    keep = np.full((nx, ny, nz, nstab, ndir), 1.)

    # VDI 3783 pt 16 sct 6.1
    # 1) Only grid points inside the largest calculation
    # area without the three outer boundary points are
    # considered.
    keep[:3, :, :, :, :] = np.nan
    keep[:, :3, :, :, :] = np.nan
    keep[-3:, :, :, :, :] = np.nan
    keep[:, -3:, :, :, :] = np.nan

    # VDI 3783 pt 16 sct 6.1
    # 2) All grid points are rejected at which the wind
    # does not rotate in the same sense with every
    # rotation of the undisturbed flow direction or at
    # which in at least one of the wind fields the wind
    # speed is below 0,5 m · s–1. The rest of the steps
    # are performed only for the remaining grid
    # points.
    for iz in range(nz):
        for istab in range(nstab):
            ff_ref, dd_ref = meteolib.wind.uv2dir(u_ref[iz, istab, :],
                                             v_ref[iz, istab, :])
            logger.debug('lvl: %4.0f, AK: %1i' % (iz,istab))
            if any(ff_ref < 0.5):
               keep[:, :, iz, istab, :] = np.nan
            else:
                for ix in range(nx):
                    for iy in range(ny):
                        ff_val, dd_val = meteolib.wind.uv2dir(
                            u_grid[ix, iy, iz, istab, :],
                            v_grid[ix, iy, iz, istab, :]
                        )
                        if any(ff_val < 0.5):
                            keep[ix, iy, iz, istab, :] = np.nan
                        elif not same_sense_rotation(dd_val, dd_ref):
                            keep[ix, iy, iz, istab, :] = np.nan
    u_keep = u_grid * keep
    v_keep = v_grid * keep

    # 3) At each grid point, the quality criteria gd (for the
    # wind direction) and gf (for the wind speed) are
    # calculated over all undisturbed flow sectors and
    # stability classes:
    u_ref3d = np.broadcast_to(u_ref, (nx, ny, nz, nstab, ndir))
    v_ref3d = np.broadcast_to(u_ref, (nx, ny, nz, nstab, ndir))
    sumw = np.sum(np.sum(u_keep + v_keep, axis=4), axis=3)
    sumw2 = np.sum(np.sum(u_keep ** 2 + v_keep ** 2, axis=4), axis=3)
    sumwr = np.sum(np.sum(u_keep * u_ref3d + v_keep * v_ref3d, axis=4), axis=3)
    sumr = np.sum(np.sum(u_ref + v_ref , axis=2), axis=1)
    sumr2 = np.sum(np.sum(u_ref ** 2 + v_ref ** 2, axis=2), axis=1)
    gd = np.full((nx, ny, nz), np.nan)
    for iz in range(nz):
        for iy in range(ny):
            for ix in range(nx):
                cov_wr = sumwr[ix, iy, iz] - sumw[ix, iy, iz] * sumr[iz]
                var_r = sumr2[iz] - sumr[iz] ** 2
                war_w = sumw2[ix, iy, iz] - sumw[ix, iy, iz] ** 2
                gd[ix, iy, iz] = (cov_wr ** 2) / (var_r * war_w)

    ff_grid = np.sqrt(u_keep ** 2 + v_keep ** 2)
    ff_ref3d = np.broadcast_to(np.sqrt(u_ref ** 2 + v_ref ** 2), np.shape(ff_grid))
    beta_v = np.mean(np.mean(ff_grid / ff_ref3d, axis=4), axis=3)
    gf = np.minimum(beta_v, 1 / beta_v)

    # 4) The quality criteria gd and gf are combined into
    # an overall criterion g = gd · gf. g always lies in
    # the interval [0,1], where 0 means no agreement
    # and 1 perfect agreement with the one-dimensional
    # reference profiles.
    g = gf * gd

    return g, gd, gf

def find_eap(g_lower):

    # 5) Within each individual contiguous region with
    # the wind direction rotating in the same sense,
    # the overall criteria g are added up to G.
    #ones = np.prod(np.prod(keep * 1, axis=4), axis=3)
    ones = np.isfinite(g_lower) * 1
    label, num_features = ndimage.label(ones)
    if num_features > 0:
        g_upper = ndimage.labeled_comprehension(g_lower,
                                                label,
                                                range(1, num_features + 1),
                                                np.nansum,
                                                float,
                                                0)

        # In the contiguous region with the largest sum G,
        # the grid point that exhibits the largest g is found.
        # This location is defined as EAP.
        g_upper_max = np.argmax(g_upper)
        # ! maximum_position raises meaningless Index error
        #   if nan values are in the array
        g_notnan = g_lower
        g_notnan[np.isnan(g_notnan)] = 0
        # ! label is 1-based but index in g_upper_max is 0-based -> add 1
        eap = ndimage.maximum_position(g_notnan,
                                       label,
                                       g_upper_max + 1)
    else:
        eap = (-1, -1)

    return eap


def plot_g(args, datx, daty, dat, pos=None):
    unit =""
    # --------------------------------
    matplotlib.rcParams.update({'font.size': 16})
    fig, ax = plt.subplots()
    fig.set_size_inches(11, 8)

    cmap_name = args["colormap"]
    dmin = np.floor(np.nanmin(dat)*10)/10
    dmax = np.ceil(np.nanmax(dat)*10)/10
    scale=dmax-dmin
    logging.debug('scale: %f' % scale)
    levels = np.arange(dmin,dmax,scale/10)
    if args['fewcols']:
        cmap = plt.get_cmap(cmap_name, len(levels) + 1)
    else:
        cmap = plt.get_cmap(cmap_name)
    if args['display'] == "contour":
        img = plt.contourf( datx, daty,
                           dat.T,
                           origin="lower",
                           levels=levels,
                           cmap=cmap,
                           extend='both'
                           )
        plt.colorbar(img, label=unit, extend='both')
    elif args['display'] == "grid":
        img = plt.pcolor(datx, daty,
                        dat.T,
                         shading="nearest",
                         cmap=cmap,
                         )
        plt.colorbar(img, label=unit, extend='both', boundaries=levels)
    logging.debug('label=: %s' % unit)

    if pos is not None:
        ix,iy = pos
        x = datx[int(ix)]
        y = daty[int(iy)]
        ax.plot(x, y, "o", markersize=10)

    # if have_topo:
    #     con = plt.contour(topx, topy, topz.T, origin="lower",
    #                       colors='black',
    #                       linewidths=0.75
    #                       )
    #     ax.clabel(con, con.levels, inline=True, fontsize=10)

    ax.set_xlabel("x in m")
    ax.set_ylabel("y in m")

    if args["plot"] == '__default__':
        plt.show()
    else:
        # if args["plot"] == '__default__':
        #     outname = os.path.splitext(infile_path)[0] + '.png'
        # else:
        #     if os.path.sep in args["plot"]:
        #         outname = args["plot"]
        #     else:
        #         outname = os.path.join(args["working_dir"], args["plot"])
        #     if not outname.endswith('.png'):
        #         outname = outname + '.png'
        outname = ""
        logger.info('writing plot: %s' % outname)
        # plt.savefig(outname, dpi=100)



def calc_ref_1d(levels, dirs):
    # z0 = 0.02 # value for LBM-DE landcover class 231 (Wiesen und Weiden)
    # as required by VDI 3783 Blatt 16 sect. 6.1
    z0 = 0.1  # to be used instead since 2023 according to UBA TEXTE 144/2023
    # "Weiterentwicklung ausgewählter methodischer Grundlagen
    #  der Schornsteinhöhenbestimmung und der
    #  Ausbreitungsrechnung nach TA Luft"
    # calculated values according to VDI 3783 Blatt 16 table 1
    #
    # \Theta_g = \frac{\partial \Theta}{\partial z}
    # in K/m
    val_theta_g = [
        0.008,
        0.0057,
        0.0032,
        0.0012,
        0.0003,
        0.0000
    ]
    # v_g
    # in m/s
    val_v_g = [
        1.6,
        1.5,
        7.8,
        5.6,
        4.2,
        3.8
    ]
    # reference height (where wind gets almost geostrophic)
    #h_ref = 250  # after Namlyso
    h_ref = np.nanmax(levels)
    # Obukhov-length
    l_ob = [_dispersion.KM2021.get_center(x, z0=z0)
               for x in range(6)]

    # shape of reference wind profiles: (nz, nstab, ndir)
    u_ref = np.full((len(levels), len(val_v_g), len(dirs)), np.nan)
    v_ref = np.full((len(levels), len(val_v_g), len(dirs)), np.nan)

    for istab in range(6):
        ww = meteolib.wind.DiabaticWind(z0=z0,
                                        u=val_v_g[istab],
                                        z=h_ref,
                                        zoL=h_ref / l_ob[istab])
        for idir, wdir in enumerate(dirs):
            for iz,z in enumerate(levels):
                if z < (ww.z0 + ww.d):
                    ff = 0
                else:
                    ff = ww.u(z)
                dd = wdir
                logger.debug(str([istab,idir,z,ff,dd]))
                (u_ref[iz, istab, idir],
                 v_ref[iz, istab, idir]) = meteolib.wind.dir2uv(ff, wdir)
    return u_ref, v_ref


def read_ref(file):
    cfdf = pd.read_table(file, skiprows=1, nrows=0, sep='\s+',
                         skipinitialspace=True,
                         quotechar="'", engine="python")
    cf1d = [x.replace('\'', '') for x in list(cfdf.columns)]
    df = pd.read_table(file, skiprows=2, header=None, index_col=0,
                       sep='\s+',
                       engine="python")
    ff_1d = df[[2 * x + 1 for x in range(len(cf1d))]]
    ff_1d.columns = cf1d
    dd_1d = df[[2 * x + 2 for x in range(len(cf1d))]]
    dd_1d.columns = cf1d
    return ff_1d, dd_1d


def main():
    args = cli()
    #ff_1d, dd_1d = read_ref('/local/data/druee/software/austaltools/TAL-Anemo/Ref1d.dat')
    wdir = wind_library(args["path"])
    file_info = wind_files(wdir)
    u_grid, v_grid, axes = read_wind(file_info, path=wdir)
    dirs = sorted(list(set(file_info[2])))
    u_ref, v_ref = calc_ref_1d(axes['z'], dirs)
    g, gd, gf = calc_quality_measure(u_grid, v_grid, u_ref, v_ref)
    n_lvl = len(axes['z'])
    eaps = np.full((n_lvl, 2),np.nan)
    for lvl in range(n_lvl):
        eaps[lvl, :] = find_eap(g[:, :, lvl])
        logger.info('level %2i: EAP %s' % (lvl, str(eaps[lvl, :])))
    selected_level = 10
    if 'plot' in args:
        plot_g(args,axes['x'], axes['y'],
               g[:,:,selected_level],
               eaps[selected_level,:])

if __name__ == "__main__":
    main()
