# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys
try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib
    except ImportError:
        sys.exit(1)

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../austaltools'))

# global variable to disable external imports
BUILDING_SPHINX = True


# Sphinx chdir()s into this file's directory (docs/) before executing it,
# so a plain relative path of 'pyproject.toml' looks for the file inside
# docs/ -- where it does not exist, since it actually lives at the
# repository root, one level up. Build the path from __file__ instead of
# relying on the current working directory, so this works no matter how
# sphinx-build is invoked.
_pyproject_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', 'pyproject.toml')
try:
    with open(_pyproject_path, 'rb') as f:
        data = tomllib.load(f)
        __title__ = data.get('project').get('name')
        authors = data.get('project').get('authors')
        __author__ = authors[0].get('name')
        __email__ = authors[0].get('email')
        __description__ = data.get('project').get('description', '')
except FileNotFoundError:
    __title__ = __author__ = __email__ = __description__ = 'Unknown'

# Determine the version to display in the documentation.
#
# austaltools/_version.py is generated by setuptools_scm only as a side
# effect of actually building/installing the package -- it does not exist
# in a bare source checkout. Because of the sys.path.insert() calls above,
# "from austaltools._version import __version__" resolves against the
# *local source tree* (which sys.path puts ahead of any installed copy),
# so it always raised ImportError and silently fell back to the literal
# string 'local' -- which is what was showing up as the version on the
# published docs, even for a released version.
#
# Reading the version from the installed distribution's metadata instead
# works correctly regardless of that sys.path shadowing, as long as the
# package itself was installed before the docs are built (as it normally
# is, e.g. by `tox`, `pip install .`, or a CI build step).
from importlib.metadata import version as _pkg_version, PackageNotFoundError

try:
    __version__ = _pkg_version(__title__ if __title__ != 'Unknown' else 'austaltools')
except PackageNotFoundError:
    # Package isn't installed at all (e.g. sphinx-build run directly
    # against an un-built checkout) -- ask setuptools_scm to compute the
    # version straight from git tags, without needing an install step.
    try:
        from setuptools_scm import get_version
        __version__ = get_version(root='..', relative_to=__file__)
    except Exception:
        __version__ = 'local'

from austaltools._metadata import __copyright__


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.mathjax',
              'sphinxarg.ext',
              'sphinx.ext.autosectionlabel',
             ]
suppress_warnings = ['autosectionlabel.*']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = __title__
copyright = __copyright__
author = __author__

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = __version__
# The full version, including alpha/beta/rc tags.
release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `to do` and `tod oList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'nature'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {'globaltoc_maxdepth': 2}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        #'globaltoc.html',
        'localtoc.html',
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'htmldoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, __title__ + u'.tex', __title__ + u' Documentation',
     __author__, u'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, __title__, __title__ + ' Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, __title__, __title__ + u' Documentation',
     __author__, __title__, u'One line description of project.',
     u'Miscellaneous'),
]



